Added generators for Rails (initializer and model)
Require the gem in a Rails app and run:

    $ rails generate redis_persistence:initializer --help
    $ rails generate redis_persistence:model  --help

----

Note: Requiring the Railtie file fails the app with:

  undefined method `config' for Redis::Persistence:Module (NoMethodError)

It has something to do with ActiveSupport::Configurable.

TODO: Investigate.